### ISSUE TITLE
[Request] LaunchBox Support

### ISSUE THREAD

**Issue by elwooha6** [romjacket/RoM-Jacket#1]
Hey, first I gotta say I love what you have here as it's a great tool. Would you be willing to add support for the LaunchBox frontend? Here is a link to their site

https://www.launchbox-app.com/

I would really appreciate it, or if it is already possible I would appreciate documentation on this. If you don't have the time don't worry about it, I'm sure I can figure something out but I didn't see anything on the documentation about this frontend so I thought I'd ask.

Thanks
~Six

**Comment by romjacket** [comment]
At the bottom of the page you'll see instructions on how to use your RoM-Jacket launchers with LaunchBox:
[http://romjacket.mudlord.info/HTPC.html](http://romjacket.mudlord.info/HTPC.html
)
Additionally, should you desire to migrate the artwork from LaunchBox to another frontend, from the main-menu:
Frontend -> MetaData ->Install ->Convert ->LaunchBox (and then select your LB installation folder.)
Artwork & media migration TO LaunchBox may come at a later date,
